# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='products/images/default.jpg', upload_to='products/images/'),
        ),
    ]
